# Generated by Django 4.1.5 on 2023-01-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Llave identificadora del medidor', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nombre del medidor', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.IntegerField(help_text='Consumo de la medición')),
                ('timestamp', models.DateTimeField(help_text='Fecha de la medición')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
        ),
    ]
